Repository jupyterlite/xeus-python-kernel, pull requests merged in 2022-06, with the labels that each got.

#23 Fix conflicts with sys prefix packages and ignore ignore_sys_prefix flag
  jupyterlite_xeus_python/env_build_addon.py
Labels: enhancement

#28 Improve docs
  README.md
  docs/conf.py
  docs/configuration.rst
  docs/index.rst
Labels: documentation

#33 Automated Changelog Entry for 0.4.1 on main
  CHANGELOG.md
Labels: documentation

#34 Fix temporary directories cleanup so that it happens after the tasks
  jupyterlite_xeus_python/env_build_addon.py
  tests/test_xeus_python_env.py
Labels: bug

#35 Automated Changelog Entry for 0.4.2 on main
  CHANGELOG.md
Labels: documentation

#41 Automated Changelog Entry for 0.5.0 on main
  CHANGELOG.md
Labels: documentation

#43 Fix plugin id
  src/index.ts
Labels: bug

#44 Simplify the kernel spec
  src/index.ts
Labels: maintenance

#45 Update README with config options
  README.md
Labels: documentation

#47 Automated Changelog Entry for 0.5.1 on main
  CHANGELOG.md
Labels: documentation

#49 Remove leading space in the replite default example
  docs/index.rst
Labels: documentation
